// ============================================================
// STACK LAYER: Frontend / Visual Logic Engine
// Blockly ships JS/Python/Lua/Dart/PHP generators — NOT C++.
// This is a purpose-built Arduino-C++ generator. Blocks emit
// loop() code by default; they hoist includes / globals /
// one-time setup() lines through the helpers below, and the
// finish() pass assembles a complete compilable sketch.
// ============================================================
import * as Blockly from 'blockly/core';

export const cppGenerator = new Blockly.Generator('CPP');

// Operator precedence (C++). Used by valueToCode for parenthesization.
export const Order = {
  ATOMIC: 0,
  UNARY: 2,        // ! - ++ --
  MULTIPLICATIVE: 3,
  ADDITIVE: 4,
  RELATIONAL: 6,   // < > <= >=
  EQUALITY: 7,     // == !=
  LOGICAL_AND: 11,
  LOGICAL_OR: 12,
  ASSIGNMENT: 14,
  NONE: 99,
};

cppGenerator.INDENT = '  ';

// ---- Sketch-section accumulators -------------------------------
// Reset per workspaceToCode run in init().
cppGenerator.init = function (workspace) {
  Object.getPrototypeOf(cppGenerator).init.call(this, workspace);
  this.includes_ = Object.create(null); // '#include <WiFi.h>'
  this.globals_ = Object.create(null);  // 'int ledcChannel_16 = 0;'
  this.setups_ = Object.create(null);   // 'pinMode(16, OUTPUT);'
  this.nameDB_ = new Blockly.Names(this.RESERVED_WORDS_);
  this.nameDB_.setVariableMap(workspace.getVariableMap());
  this.tmpVarCount_ = 0; // loop counters (i0, i1, …) unique per sketch
};

/** Deduplicated helpers — safe to call from every block instance. */
cppGenerator.addInclude = function (tag, code) { this.includes_[tag] = code; };
cppGenerator.addGlobal = function (tag, code) { this.globals_[tag] = code; };
cppGenerator.addSetup = function (tag, code) { this.setups_[tag] = code; };

// Every statement block chains to the next one via scrub_.
cppGenerator.scrub_ = function (block, code, thisOnly) {
  const next = block.nextConnection && block.nextConnection.targetBlock();
  return thisOnly || !next ? code : code + cppGenerator.blockToCode(next);
};

// Assemble the final .ino
cppGenerator.finish = function (loopCode) {
  const indent = (s) => s.split('\n').filter(Boolean).map((l) => '  ' + l).join('\n');
  const includes = Object.values(this.includes_).join('\n');
  const globals = Object.values(this.globals_).join('\n');
  const setups = indent(Object.values(this.setups_).join('\n'));

  return [
    '// Generated by Aurigen — do not edit by hand',
    includes,
    '',
    globals,
    '',
    'void setup() {',
    '  Serial.begin(115200);',
    setups,
    '}',
    '',
    'void loop() {',
    indent(loopCode || '// drag blocks into the workspace'),
    '}',
    '',
  ].filter((s) => s !== '').join('\n') + '\n';
};

// Values plugged into empty sockets.
cppGenerator.scrubNakedValue = (line) => line + ';\n';

// Reserved words so student variable names never collide with the runtime.
cppGenerator.RESERVED_WORDS_ =
  'setup,loop,Serial,HIGH,LOW,INPUT,OUTPUT,INPUT_PULLUP,delay,millis,' +
  'digitalWrite,digitalRead,analogRead,ledcSetup,ledcAttachPin,ledcWrite,' +
  'WiFi,int,float,bool,void,char,String,true,false,if,else,for,while,return';
